import React from 'react';
import { FileText, AlertCircle, CheckCircle2 } from 'lucide-react';

export const TermsOfService = () => {
  return (
    <div className="space-y-16 animate-fadeIn max-w-4xl mx-auto">
      {/* Hero Header */}
      <section className="pt-4 sm:pt-6">
        <p className="text-[var(--muted)] text-xs tracking-[0.35em] uppercase mb-6 font-medium">
          Terms of Service
        </p>
        <h1 
          className="font-display text-[var(--text)] leading-[1.05] mb-6 font-normal"
          style={{ fontSize: 'clamp(2.5rem, 6.5vw, 5.2rem)' }}
        >
          Terms &<br className="hidden sm:block" /> conditions of use
        </h1>
        <p className="text-[var(--muted)] text-base sm:text-lg max-w-xl leading-relaxed">
          Please review the terms of service governing your access to and use of the Alive Since web application.
        </p>
      </section>

      {/* Terms Content */}
      <div className="space-y-8 text-sm text-[var(--muted)] leading-relaxed border-t border-[var(--border)] pt-12">
        <div className="space-y-3">
          <h3 className="text-base text-[var(--text)] font-semibold uppercase tracking-wider">1. Acceptance of Terms</h3>
          <p>
            By accessing or using Alive Since, you agree to be bound by these Terms of Service. If you do not agree to these terms, please discontinue using the site.
          </p>
        </div>

        <div className="space-y-3">
          <h3 className="text-base text-[var(--text)] font-semibold uppercase tracking-wider">2. Purpose of Calculations</h3>
          <p>
            All calculations provided on Alive Since — including total seconds lived, heartbeats, breaths, milestone dates, and life expectancy progress — are for informational, statistical, and entertainment purposes only.
          </p>
        </div>

        <div className="space-y-3">
          <h3 className="text-base text-[var(--text)] font-semibold uppercase tracking-wider">3. Medical & Professional Disclaimer</h3>
          <p>
            Figures such as heartbeat and breath estimations are computed using standard population averages (70 bpm resting heart rate, 16 breaths per minute). Life expectancy data is derived from World Health Organization statistical tables. These metrics do not constitute medical, health, or financial advice.
          </p>
        </div>

        <div className="space-y-3">
          <h3 className="text-base text-[var(--text)] font-semibold uppercase tracking-wider">4. Intellectual Property</h3>
          <p>
            The design, typography, layout, graphic elements, and underlying codebase of Alive Since are protected under copyright and intellectual property laws. You may share screenshots or statistics generated by the site for personal or non-commercial use.
          </p>
        </div>

        <div className="space-y-3">
          <h3 className="text-base text-[var(--text)] font-semibold uppercase tracking-wider">5. Limitation of Liability</h3>
          <p>
            Alive Since is provided "as is" without warranty of any kind, express or implied. Under no circumstances shall the creators or maintainers be liable for any direct, indirect, or consequential damages arising from your use of the application.
          </p>
        </div>

        <div className="space-y-3">
          <h3 className="text-base text-[var(--text)] font-semibold uppercase tracking-wider">6. Modifications</h3>
          <p>
            We reserve the right to update these terms at any time. Continued use of the site after changes are posted constitutes acceptance of the modified terms.
          </p>
        </div>
      </div>
    </div>
  );
};
